
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "HANDS_ASSIGNMENT L_PARENTHESIS R_PARENTHESIS THROWsequence : sequence throw\n                | throwthrow : THROW\n             | HANDS_ASSIGNMENTthrow : throw '!'throw : L_PARENTHESIS sequence R_PARENTHESIS"
    
_lr_action_items = {'THROW':([0,1,2,3,4,5,6,7,8,9,],[3,3,-2,-3,-4,3,-1,-5,3,-6,]),'HANDS_ASSIGNMENT':([0,1,2,3,4,5,6,7,8,9,],[4,4,-2,-3,-4,4,-1,-5,4,-6,]),'L_PARENTHESIS':([0,1,2,3,4,5,6,7,8,9,],[5,5,-2,-3,-4,5,-1,-5,5,-6,]),'$end':([1,2,3,4,6,7,9,],[0,-2,-3,-4,-1,-5,-6,]),'R_PARENTHESIS':([2,3,4,6,7,8,9,],[-2,-3,-4,-1,-5,9,-6,]),'!':([2,3,4,6,7,9,],[7,-3,-4,7,-5,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'sequence':([0,5,],[1,8,]),'throw':([0,1,5,8,],[2,6,2,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> sequence","S'",1,None,None,None),
  ('sequence -> sequence throw','sequence',2,'p_sequence_f_sequence_throw','__SSparser.py',19),
  ('sequence -> throw','sequence',1,'p_sequence_f_sequence_throw','__SSparser.py',20),
  ('throw -> THROW','throw',1,'p_throw_THROW','__SSparser.py',28),
  ('throw -> HANDS_ASSIGNMENT','throw',1,'p_throw_THROW','__SSparser.py',29),
  ('throw -> throw !','throw',2,'p_throw_throw_question_mark','__SSparser.py',34),
  ('throw -> L_PARENTHESIS sequence R_PARENTHESIS','throw',3,'p_spatial_throws','__SSparser.py',39),
]
