
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'HANDS_ASSIGNMENT L_PARENTHESIS R_PARENTHESIS THROWsequence : sequence throw\n                | throwthrow : THROW\n             | HANDS_ASSIGNMENTthrow : L_PARENTHESIS sequence R_PARENTHESIS'
    
_lr_action_items = {'THROW':([0,1,2,3,4,5,6,7,8,],[3,3,-2,-3,-4,3,-1,3,-5,]),'HANDS_ASSIGNMENT':([0,1,2,3,4,5,6,7,8,],[4,4,-2,-3,-4,4,-1,4,-5,]),'L_PARENTHESIS':([0,1,2,3,4,5,6,7,8,],[5,5,-2,-3,-4,5,-1,5,-5,]),'$end':([1,2,3,4,6,8,],[0,-2,-3,-4,-1,-5,]),'R_PARENTHESIS':([2,3,4,6,7,8,],[-2,-3,-4,-1,8,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'sequence':([0,5,],[1,7,]),'throw':([0,1,5,7,],[2,6,2,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> sequence","S'",1,None,None,None),
  ('sequence -> sequence throw','sequence',2,'p_sequence_f_sequence_throw','__SSparser.py',19),
  ('sequence -> throw','sequence',1,'p_sequence_f_sequence_throw','__SSparser.py',20),
  ('throw -> THROW','throw',1,'p_throw_THROW','__SSparser.py',28),
  ('throw -> HANDS_ASSIGNMENT','throw',1,'p_throw_THROW','__SSparser.py',29),
  ('throw -> L_PARENTHESIS sequence R_PARENTHESIS','throw',3,'p_spetial_throws','__SSparser.py',34),
]
