
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'L_PARENTHESIS R_PARENTHESIS THROWsequence : sequence throw\n                | throwthrow : THROW'
    
_lr_action_items = {'THROW':([0,1,2,3,4,],[1,-3,-2,1,-1,]),'$end':([1,2,3,4,],[-3,-2,0,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'throw':([0,3,],[2,4,]),'sequence':([0,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> sequence","S'",1,None,None,None),
  ('sequence -> sequence throw','sequence',2,'p_sequence_f_sequence_throw','__SSparser.py',19),
  ('sequence -> throw','sequence',1,'p_sequence_f_sequence_throw','__SSparser.py',20),
  ('throw -> THROW','throw',1,'p_throw_THROW','__SSparser.py',28),
]
